output = """Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\GoodDrugs.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\GreatDrugs.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\IFeelMuchBetterNow.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\Open.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\SpellCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\SpellInventory.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\Zorch.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\Zot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\TestLoot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\AttackCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:98: warning - @return tag has no arguments.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\AttackCommand.java:37: warning - @param argument "gs" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\AttackCommand.java:37: warning - @param argument "gameMap" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\AttackCommand.java:37: warning - @param argument "creature" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\AttackCommand.java:37: warning - @param argument "target" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\BuyCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\CastCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\CommandChangeState.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\CommandChangeState.java:26: warning - @param argument "character" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\CommandPrepareAction.java:26: warning - @param argument "character" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\CommandPrepareAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\ComparableCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:22: warning - Tag @link: reference not found: PriorityBlockingQueue
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:22: warning - Tag @link: reference not found: ObjectOutputStream
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:89: warning - @return tag has no arguments.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:89: warning - Tag @link: reference not found: GameCharacter
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:89: warning - Tag @link: reference not found: GameCharacter
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\DebuffCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\DefendCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\DescheduleFlyCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\DieCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\DropCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\EquipCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\GameOverCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\LevelPlayerCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\MessageCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\MoveCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\MoveCommand.java:50: warning - @param argument "mapName" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerDataCommand.java:46: warning - @param argument "name" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerDataCommand.java:46: warning - @param argument "gender" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerDataCommand.java:46: warning - @param argument "clas" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\PlayerDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\PlayerQuitCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\RecoverCreaturesCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerQuitCommand.java:24: warning - @param argument "prepTime" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerQuitCommand.java:24: warning - @param argument "executeTime" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerQuitCommand.java:24: warning - @param argument "resetTime" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\PlayerQuitCommand.java:24: warning - @param argument "success" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\RequestPlayerDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\RequestUserDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\RescheduledDummySpell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\RespawnCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\RespawnCommand.java:52: warning - @param argument "s" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\RespawnCommand.java:52: warning - @param argument "userName" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\RespawnCommand.java:52: warning - @param argument "creatureName" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\RespawnCommand.java:52: warning - @param argument "spawnTime" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\SellCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\SendProfileCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\SendStateCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\SendStateCommand.java:25: warning - @param argument "prepTime" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\SendStateCommand.java:25: warning - @param argument "executeTime" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\SendStateCommand.java:25: warning - @param argument "resetTime" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\SingleStepCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\UserDataCommand.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\UserDataCommand.java:27: warning - @param argument "charName" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\GameScheduler.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\StandaloneServerMain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\State.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\State.java:438: warning - @return tag has no arguments.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\CubicInterpolator.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\DijkstraMap.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\State.java:324: warning - @param argument "playerName" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\server\State.java:370: warning - @param argument "playerName" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\Function.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\FunctionChain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\GameInitializer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\MutableInteger.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\TileRecord.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\UtilityArray.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\UtilityImage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\UtilityMath.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\UtilityString.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\UtilityTime.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\CharAnimations.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Creature.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Creature.java:43: warning - @param argument "ID" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Creature.java:43: warning - @param argument "baseStats" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Creature.java:43: warning - @param argument "inventory" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Fighter.java:24: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Creature.Stat.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Fighter.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Fighter.java:24: warning - Tag @link: reference not found: Gender
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Fighter.java:24: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\GameCharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\GameCharacter.Gender.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\GameCharacterTypes.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Mage.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Mage.java:27: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Monster.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\NPC.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\NPC.java:31: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Player.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Player.java:37: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Scriptable.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\Thief.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Thief.java:24: warning - Tag @link: reference not found: Gender
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Thief.java:24: warning - Tag @link: reference not found: Gender
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Thief.java:24: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\TestQuests.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileDesert.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileForest.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileMountain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TilePlain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TilePortal.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileSwamp.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileWasteland.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\TileWater.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\Listener.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:19: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:50: warning - Tag @link: reference not found: Player
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:35: warning - Tag @link: reference not found: Socket
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:50: warning - Tag @link: reference not found: Player
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\Sender.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\Server.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\Trace.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\QuestList.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\ExecutionException.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\ExecutionException.java:10: warning - Tag @link: reference not found: ASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\HasPattern.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\LexicalAnalyzer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\ParseException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\Parser.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\Token.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\TypeException.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\TypeException.java:10: warning - Tag @link: reference not found: ASTCell#execute()
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\Directions.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\GameMap.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\GameMap.BFSIterator.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\SearchState.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\TestGameCharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\TestNPC.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\TestPlayer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\Animation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\AnimationsOfACharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\AnimationsOfACharacter.ActionType.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\AnimationsOfAnAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\DrawableResource.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\client\Graphics\DrawableResource.java:31: warning - @return tag has no arguments.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\DrawableResourceAnimation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\DrawableResourceImage.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\client\Graphics\DrawableResourceImage.java:25: warning - @return tag has no arguments.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\GraphicsAbstract.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\GraphicsAbstract.GRAPHICS_TYPE.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\GraphicsCPU.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\ParametersAnimation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\ParametersFont.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\ParametersImage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\Bear.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\CrocWarrior.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\FireDragon.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\GnomeWarrior.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\MushroomMan.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\Orc.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\ProfessorLane.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\Spider.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\Troll.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\AbstractNanoParser.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:29: warning - Tag @link: reference not found: ASTCell
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:29: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:29: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:29: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @link: can't find _currToken in com.ai.AbstractNanoParser
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: can't find _currToken in com.ai.AbstractNanoParser
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:157: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @author cannot be used in constructor documentation.  It can only be used in the following types of documentation: overview, package, class/interface.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:54: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - @param argument "T" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:92: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - @param argument "T" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:113: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - @param argument "T" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:157: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:157: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:192: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:192: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:204: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:204: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:223: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:223: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:223: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:223: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\AST.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - @param argument "<T>" is not a type parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: Monster
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: NPC
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: SequenceASTCell
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:60: warning - Tag @link: reference not found: SequenceASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\CharSeqFile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ConcreteToken.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\NanoLexer.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:25: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:25: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:62: warning - Tag @link:illegal character: "60" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:62: warning - Tag @link:illegal character: "62" in "Token<T>"
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:46: warning - @param argument "raw" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:62: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoLexer.java:62: warning - @returns is an unknown tag.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\NanoParser.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:144: warning - @returns is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\NanoTokens.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\VM.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:60: warning - Tag @link: can't find loadSelf(Monster) in com.ai.VM
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:395: warning - Tag @link: can't find _playerDistances in com.ai.VM
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:622: warning - @return tag has no arguments.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:569: warning - Tag @link: can't find _selfName in com.ai.VM
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:569: warning - Tag @link: can't find _selftX in com.ai.VM
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:253: warning - @param argument "name" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:350: warning - @param argument "monster" is not a parameter name.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:395: warning - Tag @author cannot be used in method documentation.  It can only be used in the following types of documentation: overview, package, class/interface.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\VM.java:395: warning - @param argument "position" is not a parameter name.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\TestGameMap.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\TestTile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\Gerald.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\Harold.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\Helga.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\Merchant.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\Olga.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\ProfessorCastellanos.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\Tile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\TileConnection.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\TileException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\Quest.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\QuestEvent.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\QuestEvent.QuestAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\TestClientServer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\TestState.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\overview-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\package-summary.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: Monster
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: NPC
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\package-summary.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\ExecutionException.java:10: warning - Tag @link: reference not found: ASTCell
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\TypeException.java:10: warning - Tag @link: reference not found: ASTCell#execute()
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\package-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\package-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\package-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\constant-values.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\serialized-form.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\Weapon.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\SpaghettiSourceSword.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\ShortSword.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\RustyDagger.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\RolledUpSock.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\PipeCleanerOfDoom.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\Mace.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\LeadToothbrush.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\GuruSourceSword.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\Excalibur.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\class-use\BearClaws.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\Profile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\DebugServerSender.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\DebugServerListener.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\DebugServer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\DebugClientSender.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\class-use\DebugClientListener.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\class-use\GUIMain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\class-use\GUIGameCanvas.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\class-use\Controls.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\WhileASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\SymbolASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\SubtractASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\StringASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\StoreASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\SequenceASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\PrefixASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\PlusASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\OrASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\NumberASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\NOTASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\NilASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\NEQASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\MultASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\MinusASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\LTEASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\LTASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\InternalSymbolASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\IFASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\GTEASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\GTASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\ExternalSymbolASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\ExternalARefASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\EqualASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\EQASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\DivASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\CreatureASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\BooleanASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\ASTCell.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\ASTCells\ActionASTCell.java:31: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\test\TestVM.java:96: warning - Tag @link: reference not found: SequenceASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\AssignASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\ARefASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\AndASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\addASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\ActionASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\class-use\AbstractASTCell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\class-use\Traces.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\class-use\Servers.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\class-use\Senders.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\class-use\Listeners.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\class-use\GUICollisionObjectCircle.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\class-use\GUICollisionObjectBox.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\class-use\GUICollisionObject.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\class-use\JWorldDialogUser.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\class-use\JWorldDialogPortIP.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\class-use\JWorldDialogPortIP.FixedWidthTexField.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\class-use\JWorldDialogError.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\class-use\JWorldDialog.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\class-use\TestVM.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\class-use\TestParser.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\class-use\TestLexer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\class-use\TestAST.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\class-use\SwagFactory.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\class-use\Swag.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\class-use\Loot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\class-use\IllegalInventoryException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\SpellBook.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\InventorySlot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerStats.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerSpells.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerQuests.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerInventory.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerCreate.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GUIPanelPlayerBars.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\GenderIcon.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\ButtonArrow.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\class-use\ButtonArrow.ARROW_TYPE.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\class-use\ConfigParameter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\class-use\ConfigFile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\ToolTip.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanels.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanelQuit.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanelMovable.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanelMessage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanelInteractMerchant.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanelControlBar.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIPanel.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\class-use\GUIButton.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileOverlay.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileMovement.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileHighlight.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileCast.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileAttack.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrow_U.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrow_D.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowR_.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowRU.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowRD.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowL_.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowLU.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrowLD.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\class-use\TileArrow.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\ResourceLoader.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\Message.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\Message.Section.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\MainHandlerInput.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\Main.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\class-use\Main.MoveType.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\WetTowel.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\SnailMail.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\ScaleMail.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\PumpkinHelmet.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\ProperDesignMail.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\PlateMail.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\LeatherArmor.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\JUnitMail.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\GuruSourceArmor.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\ChainMailBikini.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\class-use\Armor.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\Zot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\Zorch.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\SpellInventory.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\SpellCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\Open.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\IFeelMuchBetterNow.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\GreatDrugs.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\GoodDrugs.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\Fly.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\FlameThrower.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\Defend.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\BuffStrength.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\BuffSpeed.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\BuffMagic.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\BuffIntelligence.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\BuffHealth.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\ArmageddonAndThenSome.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\class-use\AbstractSpell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\class-use\TestLoot.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\UserDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\SingleStepCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\SendStateCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\SendProfileCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\SellCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\RespawnCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\RescheduledDummySpell.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\RequestUserDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\RequestPlayerDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\RecoverCreaturesCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\PlayerQuitCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\PlayerDataCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\MoveCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\MessageCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\LevelPlayerCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\GameOverCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\EquipCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\DropCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\DieCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\DescheduleFlyCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\DefendCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\DebuffCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\ComparableCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\CommandPrepareAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\CommandChangeState.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\CastCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\BuyCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\class-use\AttackCommand.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\class-use\State.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\class-use\StandaloneServerMain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\class-use\GameScheduler.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\UtilityTime.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\UtilityString.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\UtilityMath.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\UtilityImage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\UtilityArray.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\TileRecord.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\MutableInteger.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\GameInitializer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\FunctionChain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\Function.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\DijkstraMap.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\class-use\CubicInterpolator.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Thief.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Scriptable.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Player.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\NPC.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Monster.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Mage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\GameCharacterTypes.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\GameCharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\GameCharacter.Gender.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Fighter.java:24: warning - Tag @link: reference not found: Gender
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Thief.java:24: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Fighter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Creature.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\Creature.Stat.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\class-use\CharAnimations.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\class-use\TestQuests.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileWater.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileWasteland.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileSwamp.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TilePortal.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TilePlain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileMountain.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileForest.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\class-use\TileDesert.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\class-use\Trace.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\class-use\Server.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\class-use\Sender.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\class-use\Listener.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\class-use\QuestList.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\TypeException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\Token.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\Parser.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\ParseException.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:157: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\LexicalAnalyzer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\HasPattern.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\class-use\ExecutionException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\class-use\SearchState.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\class-use\GameMap.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\class-use\GameMap.BFSIterator.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\class-use\Directions.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\class-use\TestPlayer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\class-use\TestNPC.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\class-use\TestGameCharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\ParametersImage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\ParametersFont.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\ParametersAnimation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\GraphicsCPU.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\GraphicsAbstract.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\GraphicsAbstract.GRAPHICS_TYPE.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\DrawableResourceImage.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\DrawableResourceAnimation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\DrawableResource.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\AnimationsOfAnAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\AnimationsOfACharacter.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\AnimationsOfACharacter.ActionType.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\class-use\Animation.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\Troll.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\Spider.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\ProfessorLane.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\Orc.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\MushroomMan.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\GnomeWarrior.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\FireDragon.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\CrocWarrior.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\class-use\Bear.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\VM.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\NanoTokens.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\NanoParser.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\NanoLexer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\ConcreteToken.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\CharSeqFile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\AST.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\class-use\AbstractNanoParser.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\class-use\TestTile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\class-use\TestGameMap.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\ProfessorCastellanos.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\Olga.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\Merchant.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\Helga.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\Harold.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\class-use\Gerald.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\class-use\TileException.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\class-use\TileConnection.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\class-use\Tile.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\class-use\QuestEvent.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\class-use\QuestEvent.QuestAction.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\class-use\Quest.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\class-use\TestState.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\class-use\TestClientServer.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\package-use.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: Monster
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: NPC
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: Monster
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: NPC
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\ASTCells\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\reference\package-use.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\ExecutionException.java:10: warning - Tag @link: reference not found: ASTCell
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\TypeException.java:10: warning - Tag @link: reference not found: ASTCell#execute()
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\ExecutionException.java:10: warning - Tag @link: reference not found: ASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\ai\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Dialog\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\Graphics\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\collision\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\client\GUI\panels\player\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\monsters\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\content\npcs\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\spells\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\characters\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\overlay\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\environment\tiles\terrain\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\armor\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\items\weapon\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\game\quest\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\command\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\factory\classes\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\interfaces\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\server\test\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\package-use.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\com\utilities\configfile\package-use.html...
Building index for all the packages and classes...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\overview-tree.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-1.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: Monster
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AST.java:29: warning - Tag @link: reference not found: NPC
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-2.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-3.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:133: warning - Tag @link: reference not found: Token<T>
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:157: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\AbstractNanoParser.java:171: warning - Tag @param cannot be used in inline documentation.  It can only be used in the following types of documentation: class/interface, constructor, method.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-4.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-5.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\ExecutionException.java:10: warning - Tag @link: reference not found: ASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-6.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Fighter.java:24: warning - Tag @link: reference not found: Gender
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-7.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\server\command\ComparableCommand.java:89: warning - Tag @link: reference not found: GameCharacter
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:50: warning - Tag @link: reference not found: Player
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:50: warning - Tag @link: reference not found: Player
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:50: warning - Tag @link: reference not found: Player
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:27: warning - Tag @link: reference not found: ComparableCommands
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\server\interfaces\Listener.java:43: warning - Tag @link: reference not found: ComparableCommand
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-8.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-9.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:489: warning - @NanoTokens is an unknown tag.
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-10.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-11.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-12.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-13.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-14.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-15.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\NanoParser.java:48: warning - Tag @link: reference not found: Parser
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-16.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-17.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-18.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-19.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-20.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\game\characters\Thief.java:24: warning - Tag @link: reference not found: Gender
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\reference\TypeException.java:10: warning - Tag @link: reference not found: ASTCell#execute()
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-21.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-22.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-23.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-24.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-25.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-26.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index-files\index-27.html...
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\ASTCells\ActionASTCell.java:31: warning - Tag @link: reference not found: ComparableCommand
C:\dev\Java\JWorldRepos\JWorld\src\com\ai\test\TestVM.java:96: warning - Tag @link: reference not found: SequenceASTCell
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\deprecated-list.html...
Building index for all classes...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\allclasses-frame.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\allclasses-noframe.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\index.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\overview-summary.html...
Generating C:\dev\Java\JWorldRepos\JWorld\api-doc\help-doc.html...
239 warnings
"""
for line in output.split("\n"):
    #line = line.strip()
    #if line == "": continue
    if "@" not in line: continue
    line = line.replace("\\","/")
    print line
